DROP DATABASE IF EXISTS SONGDB;

CREATE DATABASE SONGDB;

use SONGDB;

CREATE TABLE USER(

    USER_ID INT NOT NULL AUTO_INCREMENT,
    USER_EMAIL varchar(255) NOT NULL UNIQUE,
    USER_PASSWORD varchar(255) NOT NULL,
    PRIMARY KEY (USER_ID)

);

CREATE TABLE SONG(

    SONG_ID INT NOT NULL AUTO_INCREMENT,
    USER_ID INT,
    SONG_NAME varchar(255) NOT NULL UNIQUE,
    PRIMARY KEY (SONG_ID),
    FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID)

);

